blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: mailto:security@voidkey.com
    about: Please report security vulnerabilities via email instead of GitHub issues
  - name: General Questions
    url: mailto:andrew@voidkey.com
    about: For general questions or support requests